# your domain
domain: testdemoxkky.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://testdemoxkky.herokuapp.com/m/source.yaml
